### ISSUE TITLE
Flickering popover

### ISSUE THREAD

**Issue by julianobrasil** [ncsu-sat/popover#29]
@willshowell, I tried out the popover. I want to fire it on hover event.

Basically, I encapsulated it in a component like this:

```html
<div class="full-width" [satPopoverAnchorFor]="tutoriaPopover" satDisableClick
 (mouseenter)="openpopover()" (mouseleave)="closepopover()">
  {{message}}
</div>
<sat-popover #tutoriaPopover xPosition="after" [overlapAnchor]="false">
  <div class="popover-class">
      <ng-container *ngFor="let num of [1,2,3,4,5,6]">
        <br *ngIf="i > 0">
        <strong>
          item {{num}}
        </strong>
      </ng-container>
  </div>
</sat-popover>
```

and then, in **`<md-select>`**

```html
<md-option>
   <app-popover></app-popover>
</md-option>
```

I'm not sure, but I have a feeling that the flickering effect is caused by  **`(mouseenter)`**/**`(mouseleave)`** events that are being fired by many transitions between **`md-option`**/**`app-popover`**. Any ideas on how to avoid it?

![image](https://media.giphy.com/media/xT9IgLjFhGKFx88Dcs/giphy.gif)

**Comment by willshowell** [comment]
Interesting, I'll take a look. I've gone back on forth on how to support more than just clicks

1. Keep as is, where you have to `satDisableClick` the anchor
2. No default behavior... you have to setup `click` or `hover` events yourself. I doubt this would be that bad, because I think you can do it all in the template without needing boilerplate class methods.
3. Have an opt-in input like `satTriggerPopoverOn` where you can pass in `'click' | 'hover' | 'focus' | ...`

**Comment by julianobrasil** [comment]
I'm not sure the problem is with the popover.

As I have an (mouseenter)/(mouseleave), it looks like that these events are being fired one after another cyclically while I pass the mouse pointer over the **`<md-option>`**. Maybe I'm not doing doing the right thing.

I like the option 2. **`(mouseenter)="popoverTrigger.openPopover()"`** is not a hard thing to do.

**Comment by julianobrasil** [comment]
I feel like maybe this is the problem: https://stackoverflow.com/a/26103772/6433166

**Comment by julianobrasil** [comment]
Look how the pointer change from the hand to the arrow as soon as the animation runs:

![image](https://media.giphy.com/media/3o7aCQbLlwuvwg3eBG/giphy.gif)

**Comment by julianobrasil** [comment]
I saw the popover is trapping focus for accessibility reasons (for screen readers to read the options?). Does this have actually a solution without trapping the focus?

**Comment by willshowell** [comment]
I just took a look, and it's due to the backdrop overlay being added between the popover and your option list. So as soon as the `mouseenter` event occurs, the backdrop is causing it to immediately trigger `mouseleave`.

Here is the demo app working with backdrops turned off 

![hover-popover](https://user-images.githubusercontent.com/6475576/30775370-289b40a8-a060-11e7-964d-99106a4c534b.gif)





And thanks for the feedback! I think we should do the following

1. Add the ability to disable backdrop and to apply a custom backdrop class
2. Remove the default click behavior
2. Add open/close methods to the popover so you don't have to get access to the anchor. This should make it easier to set up the behavior only through the template since you already have a template reference to the popover component.

**Comment by julianobrasil** [comment]
Nice! Now I have to learn a little bit of the cdk/overlay 😃 . I'll get back when I do this.

**Comment by julianobrasil** [comment]
> Add the ability to disable backdrop and to apply a custom backdrop class

This is important, if we really want a backdrop. Does it necessary? I mean... a popover with a backdrop almost looks like an alert window. But if we want a very customizable popover, that's ok.

> Remove the default click behavior

The hover event has the tricky thing about the backdrop (that originated this issue), I think it should have this event as an opt-in to avoid people asking time after time that the component is flickering. Maybe just a hoverTriggerActivated, I'm not sure what would be better. Just a 

> Add open/close methods to the popover so you don't have to get access to the anchor. This should make it easier to set up the behavior only through the template since you already have a template reference to the popover component.

You're saying we'd have both the anchor and the popover open/close event, right? This would be great. In this case, add an **`exportAs`** to the popover.

I've been reading a little bit about portals and overlays. They're really nece.

**Comment by willshowell** [comment]
1. Setting classes is low priority, yeah. But I think having the ability to enable/disable them should be easy and obvious, for this "tooltip" use case and similar.
2. Maybe no default behavior but with `'click' | 'hover'` "prepackaged solutions"?
3. Yeah our internal use case needed the methods on the anchor, but it's now obvious how roundabout that is for a typical use case.

I suppose in general, there are two problems we are trying to solve

- a more configurable version of a tooltip (matTooltip that can contain whatever)
- a mix between a menu and a dialog (kind of a mat-menu that doesn't close on selection)

There are so many similarities between these problems... the primary differences are whether you hover or click, and whether or not you need to interact with the background via pointer-events. I'd prefer to avoid creating two separate components, but rather make it super easy to wire up `sat-popover` into any behavior you need.

**Comment by julianobrasil** [comment]
Closing this as the main problem was solved in https://github.com/ncsu-sat/popover/pull/32/commits/885d738c900cc1793abb95c43fb55e7a6e7eb025
